version: '3.8'

services:
    db:
        container_name: db
        environment:
            SA_PASSWORD: "Password123."
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1433:1433"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    order.api:
        container_name: order.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:OrderDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
            - "EventBusSettings:HostAddress=amqp://guest@rabbitmq:5672" 
        depends_on:
            - db
            - rabbitmq
        ports:
            - "8001:80"