version: '3.8'

services:
    db:
        container_name: db
        environment:
            SA_PASSWORD: "Password123."
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1433:1433"
        volumes:
            - dbdata:/var/opt/mssql

    redis:
        container_name: redis
        restart: always
        ports: 
            - "6379:6379"
        volumes:
            - redisdata:/var/opt/redis

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    order.api:
        container_name: order.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:OrderDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
            - "EventBusSettings:HostAddress=amqp://guest@rabbitmq:5672" 
        depends_on:
            - db
            - rabbitmq
        ports:
            - "8001:80"

    catalog.api:
         container_name: catalog.api
         environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:CatalogDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
            #- RedisConfiguration_Url=redis
            #- RedisConfiguration_Port=6379
            #- RedisConfiguration_Host=redis:6379
         depends_on:
            - db
            - redis
         ports:
            - "8002:80"

    identity.api:
         container_name: identity.api
         environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:UserDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
         depends_on:
            - db
         ports:
            - "8003:80"

    basket.api:
         container_name: basket.api
         environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:BasketDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
         depends_on:
            - db
         ports:
            - "8004:80"

    product.api:
         container_name: product.api
         environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:ProductDB=Server=db;Database=ECommerceDB;User Id=sa;Password=Password123.;Encrypt=False"           
         depends_on:
            - db
         ports:
            - "8005:80"

    notification.service:
         container_name: notification.service
         environment:
            - ASPNETCORE_ENVIRONMENT=Development
         ports:
            - "8006:80"
         depends_on:
            - rabbitmq

volumes:
    dbdata:
    redisdata: