version: '3.8'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest  
    
  order.api:
    image: orderingapi
    build:
      context: .
      dockerfile: src\Services\Orders\Orders.API\Dockerfile

  rabbitmq:
    image: rabbitmq:3-management  
