version: '3.8'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest  

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management 
    
  order.api:
    image: orderingapi
    build:
      context: .
      dockerfile: src\Services\Orders\Orders.API\Dockerfile

  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src\Services\Catalogs\Catalogs.API\Dockerfile

  identity.api:
    image: identityapi
    build:
      context: .
      dockerfile: src\Services\Identity\Identity.API\Dockerfile

   
