version: '3.8'

services:
  api.gateway:
     image: apigateway:latest
     build:
      context: .
      dockerfile: src\ApiGateways\WebApiGateway\Web.ApiGateway\Dockerfile  

  bff:
     image: apigateway:latest
     build:
      context: .
      dockerfile: src\ApiGateways\WebApiGateway\Web.ApiGateway\Dockerfile

  orderapi:
    image: orderapi
    build:
      context: .
      dockerfile: src\Services\Orders\Orders.API\Dockerfile
    container_name: orderapi

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src\Services\Catalogs\Catalogs.API\Dockerfile
    container_name: catalogapi

  identityapi:
    image: identityapi
    build:
      context: .
      dockerfile: src\Services\Identity\Identity.API\Dockerfile
    container_name: identityapi
 
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src\Services\Baskets\Baskets.API\Dockerfile
    container_name: basketapi

  productapi:
    image: productapi
    build:
      context: .
      dockerfile: src\Services\Products\Products.API\Dockerfile
    container_name: productapi

  notificationservice:
    image: notificationservice
    build:
       context: .
       dockerfile: src\Services\Notification\NotificationService\Dockerfile
    container_name: notificationservice
  
  paymentservice:
    image: paymentservice
    build:
       context: .
       dockerfile: src\Services\Payments\PaymentService\Dockerfile
    container_name: paymentservice

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest  

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management 
    
  consul:
     image: consul:1.15.4
     command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
     hostname: consul
     container_name: consul
   
