version: '2.1'

services:
  sql-server:
   image: mcr.microsoft.com/mssql/server:2019-latest
   container_name: sql-data
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Developer
     - MSSQL_TCP_PORT=1433
     - SA_PASSWORD=Password123.
   ports:
     - "1434:1433"
   volumes:
     - "mssql_data:/var/opt/mssql/data"
   restart: always

  orders.api:
    image: order-api
    container_name: ms-order-api
    build:
      context: .
      dockerfile: src\Services\Orders\Dockerfile
    ports:
      - "81:80"
    depends_on:
      - sql-server
    environment:
      - 'ConnectionStrings:OrderDB=Server=sql-server,1433;Database=ECommerceDB;User=sa;Password=Password123.'
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
     
volumes:
  mssql_data: